// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrate/introspect need a direct (non-pooled) connection — PgBouncer's
    // transaction mode doesn't support the DDL/advisory-lock behavior Migrate needs.
    url: process.env["DIRECT_URL"],
  },
});
